<?php

$PROJECT_DIRECTORY_PATH = dirname(__FILE__);
$PROJECT_DIRECTORY_NAME = basename(dirname(__FILE__));

$PROJECT_HOSTNAME = $_SERVER['HTTP_HOST'];
$PROJECT_PORT = $_SERVER['SERVER_PORT'];
$PROJECT_SCHEME = $_SERVER['REQUEST_SCHEME'];

$PROJECT_URL = "$PROJECT_SCHEME://$PROJECT_HOSTNAME:$PROJECT_PORT/$PROJECT_DIRECTORY_NAME";